#This pod can not run because the image is in private repo
apiVersion: v1
kind: Pod
metadata:
  name: pod-private-image-with-credential
spec:
  containers:
  - name: private-nginx
    image: rockman88v/private-nginx:latest
  imagePullSecrets:
  - name: my-dockerhub-secret  # Sử dụng pull secret
