[all]
master1  ansible_host=192.168.10.21      ip=192.168.10.21
master2  ansible_host=192.168.10.22      ip=192.168.10.22
master3  ansible_host=192.168.10.23      ip=192.168.10.23
worker1 ansible_host=192.168.10.24      ip=192.168.10.24
worker2 ansible_host=192.168.10.25      ip=192.168.10.25

[kube_control_plane]
master1
master2
master3

[etcd]
master1
master2
master3

[kube_node]
worker1
worker2

[calico_rr]

[k8s_cluster:children]
kube_control_plane
kube_node
calico_rr