apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app:  car
  name: car
  namespace: demo
spec:
  containers:  
  - image: rockman88v/viettq-web:latest
    name: car
    env:
    - name: APPNAME
      value: "car"
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app:  train
  name: train
  namespace: demo
spec:
  containers:  
  - image: rockman88v/viettq-web:latest
    name: train
    env:
    - name: APPNAME
      value: "train"
---
apiVersion: v1
kind: Service
metadata:  
  labels:
    app:  car
  name: car
  namespace: demo
spec:
  internalTrafficPolicy: Cluster  
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app:  car
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:  
  labels:
    app:  train
  name: train
  namespace: demo
spec:
  internalTrafficPolicy: Cluster  
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app:  train
  type: ClusterIP  