Vagrant.configure("2") do |config|

  nodes = [    
    {
      name: "master1",
      ip: "192.168.100.61",
      cpu: 2,
      mem: 4096
    },
    {
      name: "master2",
      ip: "192.168.100.62",
      cpu: 2,
      mem: 4096
    },
    {
      name: "master3",
      ip: "192.168.100.63",
      cpu: 2,
      mem: 4096
    },
    {
      name: "worker1",
      ip: "192.168.100.64",
      cpu: 2,
      mem: 4096
    },
    {
      name: "worker2",
      ip: "192.168.100.65",
      cpu: 2,
      mem: 4096
    }
  ]

  nodes.each do |node|

    config.vm.define node[:name] do |machine|

      machine.vm.box = "bento/ubuntu-24.04"

      machine.vm.hostname = node[:name]

      machine.vm.network "private_network",
        ip: node[:ip],
		vmware__network_name: "VMnet1"

      machine.vm.provider "vmware_desktop" do |v|
        v.vmx["memsize"] = node[:mem].to_s
        v.vmx["numvcpus"] = node[:cpu].to_s
      end

      machine.vm.provision "shell",
        path: "bootstrap.sh"

    end
  end
end