replicaCount: 1
nfs:
  server: 192.168.10.31
  path: /data/retain
  reclaimPolicy: Retain
storageClass:
  create: true
  provisionerName: viettq-nfs-storage-retain-provisioner
  defaultClass: true
  name: nfs-subdir-retain
  allowVolumeExpansion: true
  reclaimPolicy: Retain
  archiveOnDelete: true
  accessModes: ReadWriteOnce
  volumeBindingMode: Immediate  