replicaCount: 1
nfs:
  server: 192.168.10.31
  path: /data/delete
  volumeName: nfs-subdir-external-provisioner-root
  reclaimPolicy: Delete

# For creating the StorageClass automatically:
storageClass:
  create: true
  provisionerName: viettq-nfs-storage-delete-provisioner
  defaultClass: false
  name: nfs-subdir-delete
  allowVolumeExpansion: true
  reclaimPolicy: Delete
  archiveOnDelete: false
  accessModes: ReadWriteOnce
  volumeBindingMode: Immediate