{
 "title": "Microservice API Metrics3",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total[5m]))",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "Request Count per API",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (exported_endpoint) (increase(http_requests_total[5m]))",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Latency (p95) by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, exported_endpoint))",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "5xx Error Rate for /api/payment",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{exported_endpoint=\"/api/payment\", http_status=~\"5..\"}[5m])) / sum(rate(http_requests_total{exported_endpoint=\"/api/payment\"}[5m]))",
     "legendFormat": "Error Rate (5xx)"
    }
   ]
  }
 ]
}