# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-app
  template:
    metadata:
      labels:
        app: metrics-app
    spec:
      containers:
      - name: app
        image: rockman88v/metrics-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: USER_MIN
          value: "0.4"
        - name: USER_MAX
          value: "0.6"
        - name: ORDER_MIN
          value: "0.1"
        - name: ORDER_MAX
          value: "0.6"
        - name: PAYMENT_MIN
          value: "0.2"
        - name: PAYMENT_MAX
          value: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-app
  labels:
    app: metrics-app
spec:
  selector:
    app: metrics-app
  ports:
  - name: http
    port: 80
    targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metrics-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: metrics-app.vietdevops.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: metrics-app
            port:
              number: 80
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-app-servicemonitor  
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: metrics-app  
  endpoints:
    - port: http  
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s

