apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: metrics-app-rules
  namespace: appteam1
  labels:
    release: prometheus
spec:
  groups:
    - name: metrics-app.rules
      rules:
        - alert: HighLatencyUserAPI
          expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{endpoint="/api/user"}[5m])) by (le)) > 0.5
          for: 2m
          labels:
            severity: warning
            owner: appteam1
          annotations:
            summary: "High response time on /api/user"
            description: "p95 latency for /api/user > 0.5s for 2 minutes"

        - alert: HighLatencyOrderAPI
          expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{endpoint="/api/order"}[5m])) by (le)) > 0.6
          for: 2m
          labels:
            severity: warning
            owner: appteam1
          annotations:
            summary: "High response time on /api/order"
            description: "p95 latency for /api/order > 0.6s for 2 minutes"

        - alert: HighLatencyPaymentAPI
          expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{endpoint="/api/payment"}[5m])) by (le)) > 0.7
          for: 2m
          labels:
            severity: warning
            owner: appteam1
          annotations:
            summary: "High response time on /api/payment"
            description: "p95 latency for /api/payment > 0.7s for 2 minutes"

        - alert: HighErrorRatePaymentAPI
          expr: |
            sum(rate(http_requests_total{endpoint="/api/payment", http_status=~"5.."}[5m]))
            /
            sum(rate(http_requests_total{endpoint="/api/payment"}[5m])) > 0.2
          for: 2m
          labels:
            severity: critical
            owner: appteam1
          annotations:
            summary: "High error rate on /api/payment"
            description: "More than 20% of requests to /api/payment returned 5xx in the last 5 minutes"
