{{- if .Values.certificates.enable -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
spec:
  dnsNames:
    {{- range .Values.certificates.dnsNames }}
    - {{ . | quote }}
    {{- end }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  renewBefore: 360h0m0s
  secretName: {{ .Values.certificates.targetSecretName }}
{{- end }}
