[k8s]
master1 ansible_host=192.168.100.61 node_role=master keepalived_priority=101
master2 ansible_host=192.168.100.62 node_role=master keepalived_priority=100
master3 ansible_host=192.168.100.63 node_role=master keepalived_priority=99
worker1 ansible_host=192.168.100.64 node_role=worker
worker2 ansible_host=192.168.100.65 node_role=worker

[master_init]
master1

[master_join]
master2
master3

[masters]
master1
master2
master3

[workers]
worker1
worker2

[loadbalancer]
lb-svr ansible_host=192.168.100.60 node_role=lb

[k8s:children]
masters
workers

[k8s:vars]
ansible_user=vagrant
ansible_password=vagrant
ansible_become=true
ansible_become_password=vagrant
